spring:
  config:
    import:
      - "./env/datasource.yml"
      - "./env/jpa.yml"
      - "./env/s3.yml"
  datasource:
    driver-class-name: org.h2.Driver
    url: ${database_url}
    username: ${database_username}
    password: ${database_password}

  jpa:
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 10MB # 업로드된 파일에 대한 최대 허용 크기
      max-request-size: 10MB   # multipart/form-data 요청에 대한 최대 허용 크기

cloud:
  aws:
    s3:
      bucket: ${aws_bucket}
    credentials:
      access-key: ${aws_accessKey}
      secret-key: ${aws_secretKey}
    region:
      static: ap-northeast-2
    stack:
      auto: false

server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

env-variable:
  client-url: https://softeerbootcamp-3nd.github.io/softee5-15zizo-FE/