spring:
  config:
    import:
      - "./env/datasource.yml"
      - "./env/jpa.yml"
      - "./env/s3.yml"
  datasource:
    driver-class-name: org.h2.Driver
    url: ${database_url}
    username: ${database_username}
    password: ${database_password}

  jpa:
    hibernate:
      ddl-auto: create
cloud:
  aws:
    s3:
      bucket: ${aws_bucket}
    credentials:
      access-key: ${aws_accessKey}
      secret-key: ${aws_secretKey}
    region:
      static: ap-northeast-2
    stack:
      auto: false


